- name: myplay1
  hosts: localhost
  become: true
  connection: local
  vars:
    my_port: 90
    my_path: /var/www/html/myweb
  tasks:
   - name: install nginx
     apt: name=nginx  state=present
   - name: start nginx service
     service: name=nginx state=started
   - name: create a directory
     file: path=/var/www/html/myweb  state=directory
   - name: copy file
     copy: src=./index.html  dest=/var/www/html/myweb
   - name: copy configuration file
     template:
       src: ./mynginx.conf
       dest: /etc/nginx/sites-enabled/default
   - name: reload nginx
     service:
       name: nginx
       state: reloaded
